language: node_js

node_js:
  - "11"

install:
  - npm install

notifications:
  email:
    recipients:
      - chw644@hotmail.com
    on_success: always
    on_failure: always

branches:
  only:
    - master
